<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240521182234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE browsing_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, history_id INT NOT NULL, visited_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_58FFA4C7DE18E50B ON browsing_history (product_id_id)');
        $this->addSql('CREATE INDEX IDX_58FFA4C79D86650F ON browsing_history (user_id_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE coupon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, coupon_id INT NOT NULL, code VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, discount_amount NUMERIC(10, 5) NOT NULL, discount_type VARCHAR(255) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, order_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, total NUMERIC(10, 5) NOT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F52993989D86650F ON "order" (user_id_id)');
        $this->addSql('CREATE TABLE order_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_detail_id INT NOT NULL, quantity INT NOT NULL, price NUMERIC(10, 5) NOT NULL, order_id_id INT DEFAULT NULL, product_id_id INT DEFAULT NULL, store_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ED896F46FCDAEAAA ON order_detail (order_id_id)');
        $this->addSql('CREATE INDEX IDX_ED896F46DE18E50B ON order_detail (product_id_id)');
        $this->addSql('CREATE INDEX IDX_ED896F4637AC84E ON order_detail (store_id_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payment_id INT NOT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount NUMERIC(10, 5) NOT NULL, method VARCHAR(255) NOT NULL, order_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6D28840DFCDAEAAA ON payment (order_id_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, price NUMERIC(10, 5) NOT NULL, stock_quantity INT NOT NULL, image_url VARCHAR(255) DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id_id INT DEFAULT NULL, store_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD9777D11E ON product (category_id_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD37AC84E ON product (store_id_id)');
        $this->addSql('CREATE TABLE product_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, review_id INT NOT NULL, rating INT NOT NULL, comment VARCHAR(255) NOT NULL, review_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1B3FC062DE18E50B ON product_review (product_id_id)');
        $this->addSql('CREATE INDEX IDX_1B3FC0629D86650F ON product_review (user_id_id)');
        $this->addSql('CREATE TABLE recommendation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recommendation_id INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_433224D2DE18E50B ON recommendation (product_id_id)');
        $this->addSql('CREATE INDEX IDX_433224D29D86650F ON recommendation (user_id_id)');
        $this->addSql('CREATE TABLE returns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, return_id INT NOT NULL, return_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, reason VARCHAR(255) NOT NULL, order_id_id INT DEFAULT NULL, product_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8B164CA5FCDAEAAA ON returns (order_id_id)');
        $this->addSql('CREATE INDEX IDX_8B164CA5DE18E50B ON returns (product_id_id)');
        $this->addSql('CREATE TABLE shipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shipment_id INT NOT NULL, shipment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, carrier VARCHAR(255) NOT NULL, tracking_number VARCHAR(255) NOT NULL, order_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2CB20DCFCDAEAAA ON shipment (order_id_id)');
        $this->addSql('CREATE TABLE store (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, store_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FF575877A76ED395 ON store (user_id)');
        $this->addSql('CREATE TABLE store_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, review_id INT NOT NULL, rating INT NOT NULL, comment VARCHAR(255) NOT NULL, review_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D54175037AC84E ON store_review (store_id_id)');
        $this->addSql('CREATE INDEX IDX_1D5417509D86650F ON store_review (user_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, sex VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USER_ID ON "user" (user_id)');
        $this->addSql('CREATE TABLE wishlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, wishlist_id INT NOT NULL, added_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9CE12A31DE18E50B ON wishlist (product_id_id)');
        $this->addSql('CREATE INDEX IDX_9CE12A319D86650F ON wishlist (user_id_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE browsing_history ADD CONSTRAINT FK_58FFA4C7DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE browsing_history ADD CONSTRAINT FK_58FFA4C79D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993989D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_detail ADD CONSTRAINT FK_ED896F46FCDAEAAA FOREIGN KEY (order_id_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_detail ADD CONSTRAINT FK_ED896F46DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_detail ADD CONSTRAINT FK_ED896F4637AC84E FOREIGN KEY (store_id_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DFCDAEAAA FOREIGN KEY (order_id_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD9777D11E FOREIGN KEY (category_id_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD37AC84E FOREIGN KEY (store_id_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC062DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_review ADD CONSTRAINT FK_1B3FC0629D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D2DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D29D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE returns ADD CONSTRAINT FK_8B164CA5FCDAEAAA FOREIGN KEY (order_id_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE returns ADD CONSTRAINT FK_8B164CA5DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shipment ADD CONSTRAINT FK_2CB20DCFCDAEAAA FOREIGN KEY (order_id_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store ADD CONSTRAINT FK_FF575877A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_review ADD CONSTRAINT FK_1D54175037AC84E FOREIGN KEY (store_id_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_review ADD CONSTRAINT FK_1D5417509D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wishlist ADD CONSTRAINT FK_9CE12A31DE18E50B FOREIGN KEY (product_id_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wishlist ADD CONSTRAINT FK_9CE12A319D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE browsing_history DROP CONSTRAINT FK_58FFA4C7DE18E50B');
        $this->addSql('ALTER TABLE browsing_history DROP CONSTRAINT FK_58FFA4C79D86650F');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993989D86650F');
        $this->addSql('ALTER TABLE order_detail DROP CONSTRAINT FK_ED896F46FCDAEAAA');
        $this->addSql('ALTER TABLE order_detail DROP CONSTRAINT FK_ED896F46DE18E50B');
        $this->addSql('ALTER TABLE order_detail DROP CONSTRAINT FK_ED896F4637AC84E');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DFCDAEAAA');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD9777D11E');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD37AC84E');
        $this->addSql('ALTER TABLE product_review DROP CONSTRAINT FK_1B3FC062DE18E50B');
        $this->addSql('ALTER TABLE product_review DROP CONSTRAINT FK_1B3FC0629D86650F');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D2DE18E50B');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D29D86650F');
        $this->addSql('ALTER TABLE returns DROP CONSTRAINT FK_8B164CA5FCDAEAAA');
        $this->addSql('ALTER TABLE returns DROP CONSTRAINT FK_8B164CA5DE18E50B');
        $this->addSql('ALTER TABLE shipment DROP CONSTRAINT FK_2CB20DCFCDAEAAA');
        $this->addSql('ALTER TABLE store DROP CONSTRAINT FK_FF575877A76ED395');
        $this->addSql('ALTER TABLE store_review DROP CONSTRAINT FK_1D54175037AC84E');
        $this->addSql('ALTER TABLE store_review DROP CONSTRAINT FK_1D5417509D86650F');
        $this->addSql('ALTER TABLE wishlist DROP CONSTRAINT FK_9CE12A31DE18E50B');
        $this->addSql('ALTER TABLE wishlist DROP CONSTRAINT FK_9CE12A319D86650F');
        $this->addSql('DROP TABLE browsing_history');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE order_detail');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_review');
        $this->addSql('DROP TABLE recommendation');
        $this->addSql('DROP TABLE returns');
        $this->addSql('DROP TABLE shipment');
        $this->addSql('DROP TABLE store');
        $this->addSql('DROP TABLE store_review');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE wishlist');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
